#!/usr/bin/env bash
# Script that installs Nginx service
sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
if ps aux | grep -q '[n]ginx'; then
	sudo service nginx restart
else
	sudo service nginx start
fi
