#!/usr/bin/env bash
# Script that installs Nginx service and configures redirection

# Install Nginx if it's not already installed
if ! command -v nginx &>/dev/null; then
    sudo apt-get update -y
    sudo apt-get install -y nginx
fi

# Create a custom Nginx configuration file for the redirection
sudo sh -c 'cat > /etc/nginx/sites-available/redirect_me' <<EOF
server {
    listen 80;
    server_name 54.237.53.109;

    location /redirect_me {
        return 301 https://www.github.com/Reliccode/;
    }


}
EOF

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration and reload Nginx
sudo nginx -t
sudo systemctl reload nginx

# Create the "Hello World!" index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx to apply both the redirection and index.html changes
sudo systemctl restart nginx
