#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Reliccode permanent;/" /etc/nginx/sites-available/default
if ps aux | grep -q '[n]ginx'; then
	sudo service nginx restart
else
	sudo service nginx start
fi
