#!/usr/bin/env bash
# Script that configures Nginx for a custom 404 page

# Install Nginx if it's not already installed
if ! command -v nginx &>/dev/null; then
    sudo apt-get update -y
    sudo apt-get install -y nginx
fi

# Remove the default Nginx configuration if it exists
if [ -e /etc/nginx/sites-enabled/default ]; then
    sudo rm /etc/nginx/sites-enabled/default
fi

# Create a custom Nginx configuration file for the 404 page
sudo sh -c 'cat > /etc/nginx/sites-available/custom_404' <<EOF
server {
    listen 80 default_server;
    server_name 54.237.53.109;

    location / {
        return 404 "Ceci n'est pas une page\n";
    }
}
EOF

# Create a symbolic link to enable the custom 404 page configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test Nginx configuration and reload Nginx
sudo nginx -t -c /etc/nginx/nginx.conf -g "include /etc/nginx/sites-enabled/*;"
sudo systemctl reload nginx

# Create the "Hello World!" index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx to apply changes
sudo systemctl restart nginx
